# Generated by Django 3.0.7 on 2020-07-08 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catgory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('分类', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('昵称', models.CharField(blank=True, default='未命名', max_length=200, null=True)),
                ('手机', models.CharField(blank=True, max_length=200, null=True)),
                ('QQ', models.CharField(blank=True, max_length=200, null=True)),
                ('地址', models.CharField(blank=True, max_length=200, null=True)),
                ('头像', models.ImageField(blank=True, null=True, upload_to='')),
                ('用户', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('图片', models.ImageField(upload_to='')),
                ('名称', models.CharField(max_length=200)),
                ('简介', models.TextField(blank=True, null=True)),
                ('价格', models.IntegerField(blank=True, null=True)),
                ('时间', models.DateTimeField(auto_now_add=True)),
                ('分类', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Catgory')),
                ('发布人', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('创建时间', models.TimeField(auto_now_add=True)),
                ('商品', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Good')),
                ('收藏人', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
