# Generated by Django 3.0.7 on 2020-07-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200708_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catgory',
            options={'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='collect',
            options={'ordering': ['-id'], 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-id'], 'verbose_name_plural': '商品'},
        ),
    ]
