# Generated by Django 3.0.7 on 2020-07-10 14:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200708_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='介绍',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
