# Generated by Django 3.0.7 on 2020-07-10 17:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_good_介绍'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='介绍',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
