# Generated by Django 3.0.7 on 2020-09-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200710_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='介绍',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='价格',
            field=models.TextField(blank=True, null=True),
        ),
    ]
